dump-keys-sqlite3: add missing validation, optimize loop
Verify that data file is readable.

Query all active vbuckets from bucket-0.mb first, then
bucket-1.mb, etc., instead of going in vbucket order. This *may*
help use filesystem cache more effectively.

diff --git a/dump-keys-sqlite3 b/dump-keys-sqlite3
--- a/dump-keys-sqlite3
+++ b/dump-keys-sqlite3
@@ -3,7 +3,7 @@
 die () { echo "FATAL ERROR:" "$@" >&2; exit 2; }
 
 sqlite=/opt/couchbase/bin/sqlite3
-if [ ! -x "$sqlite" ]; then die "Can't find sqlite command-line executable at '$sqlite'"; fi
+[ -x "$sqlite" ] || die "Can't find sqlite command-line executable at '$sqlite'"
 
 if [ $# -ne 1 ]; then
     echo "Usage: $0 /path/to/bucket-data/bucket"
@@ -12,12 +12,17 @@ if [ $# -ne 1 ]; then
 fi
 
 bucket=$1
+[ -r "$bucket" ] || die "Can't read database file '$bucket'"
 
 active=`"$sqlite" "$bucket" 'SELECT vbid FROM vbucket_states WHERE state LIKE "active"' | xargs`
 
 echo "# $active"
-for vbid in $active; do
-    part=`expr "$vbid" \% 4`
-    file="$bucket-$part.mb"
-    "$sqlite" "$file" "SELECT hex(k) FROM kv_$vbid"
+for part in 0 1 2 3; do
+    # Process each bucket-{0,1,2,3}.mb file in turn, to
+    # take more advantage of filesystem buffer
+    for vbid in $active; do
+        [ `expr "$vbid" \% 4` -eq $part ] || continue
+        file="$bucket-$part.mb"
+        "$sqlite" "$file" "SELECT hex(k) FROM kv_$vbid"
+    done
 done
